### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [4]:
import numpy as np  # import the NumPy library and alias it as np.
A = np.array([1, 2, 3, 4, 5])  # create an array containing the specified elements.
print(A) # output the contents of array A.
print("Shape:", A.shape) # display the dimensions of array A.
print("Max:", A.max()) # show the maximum value among the elements in array A.
print("Max using numpy:", np.max(A)) # output the maximum value among the elements in array A using NumPy's max function.

[1 2 3 4 5]
Shape: (5,)
Max: 5
Max using numpy: 5


In [5]:
B = np.ones((5, 5), dtype=int) # B is a 5x5 array filled with integer values, each initialized to one.
print(B) # pprint the contents of array B.
print(B.shape) # print the dimensions of array B.
print(B.size) # print the total number of elements in array B.
print(np.ndim(B)) # print the number of dimensions in array B.

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(5, 5)
25
2


### Exercise

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [6]:
import numpy as np
A1 = np.arange(10, 70, 2) # generate an array starting from 10 up to (but not including) 70, with a step of 2.

#print(A1) # display the array A1 containing 30 elements.
#print(A1.size) # output the total number of elements in array A1.

A2 = (A1 * 3) # multiply each element of array A1 by 3.
print(A2) # print the resulting array A2.

[ 30  36  42  48  54  60  66  72  78  84  90  96 102 108 114 120 126 132
 138 144 150 156 162 168 174 180 186 192 198 204]


### Exercise

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.


In [ ]:
import numpy as np
array4D = np.random.randint(0, 13, size=(3, 4, 5, 6))
print(array4D) # pprint the array
print(np.ndim(array4D)) # print the dimensions of the array using the function of numpy
print(array4D.shape) # print size of each dimension
print(array4D.size) # print the total size of the array

[[[[ 4 12  6  9  7 11]
   [ 6 12  1  7  5  2]
   [ 0  1  3 10 11 10]
   [ 6 10  8  3  9  1]
   [ 9  8 11  7 12  4]]

  [[ 0  9  8  6 10  3]
   [ 4  9  8  5  7  8]
   [ 8 12 10 12 11  4]
   [ 3  3  3  1  2  6]
   [ 6 12 12  4  1 12]]

  [[ 2  7  9 11  7  8]
   [ 1 11  8  0 11  3]
   [ 0 12  4  6  9  0]
   [ 2 10 10  9  6 12]
   [ 4  7 11  5  8  0]]

  [[ 9  9  7  4  9 10]
   [ 4  8  9  2  2 12]
   [ 2  8  0  5 10  5]
   [ 2  0 11  2  8  6]
   [11 11  4  9  5  9]]]


 [[[ 9 12  2  7  4  5]
   [11  2 12  9  5  3]
   [12  3  1  4  0 10]
   [ 4  9 10  1  3  7]
   [ 9  6 11  4  6  1]]

  [[12 12  4  1  2  9]
   [ 9  3  3  0  4  8]
   [12  8  6  4 11  9]
   [ 2  8  6  3  4  2]
   [ 7 10  0  7  2  0]]

  [[ 5  8  6  7  3  2]
   [ 7 11 10  1 11  7]
   [ 5  3 12  5  4  1]
   [ 4  5 11 12  4  1]
   [11  6 12 11  8  4]]

  [[12 11  7  1  1 11]
   [ 7  7  7  1 11  3]
   [ 8  3  3  1 12  6]
   [ 3  6 12  7  4 11]
   [ 4  1  1  6  8 11]]]


 [[[ 5  0 12  6  2  5]
   [ 5 12 11 11  0  3]
   [ 8  1  7  

In [ ]:
max4D = np.max(array4D, axis=(0, 1, 2, 3)) # Using the function of numpy to get the maximum number for each dimensions
print(max4D) # Print the maximum number for each dimension

12


In [ ]:
multiply4D = array4D * 4 # Multipy each array with 4
print(multiply4D) # Each element in the array4D is multiplied by 4, resulting in a new array where all values are four times larger than the original values.

[[[[16 48 24 36 28 44]
   [24 48  4 28 20  8]
   [ 0  4 12 40 44 40]
   [24 40 32 12 36  4]
   [36 32 44 28 48 16]]

  [[ 0 36 32 24 40 12]
   [16 36 32 20 28 32]
   [32 48 40 48 44 16]
   [12 12 12  4  8 24]
   [24 48 48 16  4 48]]

  [[ 8 28 36 44 28 32]
   [ 4 44 32  0 44 12]
   [ 0 48 16 24 36  0]
   [ 8 40 40 36 24 48]
   [16 28 44 20 32  0]]

  [[36 36 28 16 36 40]
   [16 32 36  8  8 48]
   [ 8 32  0 20 40 20]
   [ 8  0 44  8 32 24]
   [44 44 16 36 20 36]]]


 [[[36 48  8 28 16 20]
   [44  8 48 36 20 12]
   [48 12  4 16  0 40]
   [16 36 40  4 12 28]
   [36 24 44 16 24  4]]

  [[48 48 16  4  8 36]
   [36 12 12  0 16 32]
   [48 32 24 16 44 36]
   [ 8 32 24 12 16  8]
   [28 40  0 28  8  0]]

  [[20 32 24 28 12  8]
   [28 44 40  4 44 28]
   [20 12 48 20 16  4]
   [16 20 44 48 16  4]
   [44 24 48 44 32 16]]

  [[48 44 28  4  4 44]
   [28 28 28  4 44 12]
   [32 12 12  4 48 24]
   [12 24 48 28 16 44]
   [16  4  4 24 32 44]]]


 [[[20  0 48 24  8 20]
   [20 48 44 44  0 12]
   [32  4 28 2